### ISSUE TITLE
accept saved R object as input

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmm-webapp#14]
Sometimes user may have processed data in R and want to load it into the web app. 

Because there are lots of possible ways of saving data, and the app need to have some assumptions for data, it's better to follow some rules.

- Save single R object in `RDS` format with `saveRDS`. The more commonly used `save` write R objects with their names, thus importing a `Rda` file could override existing objects with same name. It's also more predictable when there is only one object in file.
- The object could be single `ctmm` `telemetry` object, or a list of them.
- It's better not to take a data frame imported from csv, because we want to import data with `ctmm::as.telemetry` to go through a lot of clean up and other processes. 

Another more flexible related usage is to have each `page` of the web app packaged as a function, then user can call any function with his/her own data, run certain features on it.

This is only about input data. For states in session, we have plan to save/restore states between sessions, and work report feature which can also save/restore.

**Comment by jmcalabrese** [comment]
For most users, I think the save/restore state functionality will be more important than being able to save modified versions of a dataset. For longer sequences of analyses, I think many folks will want the ability to pick up where they left off, or to go back and double check particular analyses/results. And of course, having a report documenting everything that was done will also be very useful.

**Comment by xhdong-umd** [comment]
Closed temporarily to focus on active tasks.
