### ISSUE TITLE
Mismatch between movebank study and information shown

### ISSUE THREAD

**Issue by vestlink** [ctmm-initiative/ctmm-webapp#15]
When i log using the movebank login feature in the import data pane it lists correctly the studies where i am data manager, but the infomartion fetched from movebank is wrong and the data cannot be downloaded.

<img width="1130" alt="movebank login" src="https://cloud.githubusercontent.com/assets/20791068/25146530/8184ec68-2474-11e7-95d4-2e0a05a4f164.png">

**Comment by vestlink** [comment]
error message from RStudio:

Error in fread(res$res_cont, sep = ",", nrows = 5) : 
  Expected sep (',') but new line, EOF (or other non printing character) ends field 0 when detecting types from point 0: <span style="font-weight:bold;font-style:italic;">License Terms: </span>These data have been published by the Movebank Data Repository with DOI

**Comment by xhdong-umd** [comment]
@vestlink I added this feature but have no way to test it since either me or Chris are not data manager of any study in movebank.

I saw the details of study seemed to be another study "16615296	(EBD) Lesser Kestrels" instead of the one you selected. If you don't use the check box "data manager", can you select the study you want and download the detail correctly?

**Comment by xhdong-umd** [comment]
@vestlink , I did some change to the code and updated the repo. Can you test if it works now?

**Comment by vestlink** [comment]
I'll give it a go

**Comment by vestlink** [comment]
The study details are correct but the data is still the lesser kestrel.

When searching for my study i get no result, only when ticking off "Only show I'm data manager".

Could be a mis match in movebank.

I could lend you my login credentials for you to use during the development of this app. If it is ok with movebank policy...

**Comment by xhdong-umd** [comment]
@vestlink Can you try again? It should be fixed now.

I spent a lot of time on the movebank download feature, but in the end the downloaded data only have some core columns, not as complete as the csv from web site. This may cause some problems in the analysis later.

I also asked movebank to provide a direct download of the csv file.

**Comment by vestlink** [comment]
works fine now 👍
