### ISSUE TITLE
Suggestion for future feature

### ISSUE THREAD

**Issue by vestlink** [ctmm-initiative/ctmm-webapp#16]
Hi.
I hope it is ok that i suggest future feature suggestions here.

When using the variogram to establish the time an animal potentially needs to traverse its home range, you obtain a time and area. Lets say my animal uses approx 5 days to travers 2 km2. My animal is sampled for 60 days. Would it make sense to then devide the 60 days into e.g. 12 bins in order to be able to e.g. calculate overlaps from period 1 through 12? Hebivores in e.g. alpine invironments are believed to follow the seasonal greenup. The division of the total into bins would allow the user to, when enriching the akde with environmental varibles (DEM, ndvi, slope, activity classes and so on), analyse how the area use might co-vary with its environment.

Nicolai

**Comment by jmcalabrese** [comment]
With 60 days of data and a 5 day range crossing time, you have an effective sample size for home range estimation of ~60/5=12. Each of your 12 bins would then have N_e = 1, and you should not expect to get reliable home range estimates with such a small N_e. So no, I don't think it would be a good idea to do this. Understanding how the environment influences movement is, of course, super important, and we are working on other ways of making that link.

**Comment by xhdong-umd** [comment]
@vestlink this is the place for bug reports, feature suggestions, feel free to add any thought.

I'm not really knowledgeable about this topic, though the time subsetting page have the sampling time binned into N groups and colored points in each group with different color. So you can adjust the bin count N to 12 to see if there is obvious pattern in the scatterplot. 

We didn't make the the bin interval moveable yet, so you cannot keep same bin count and shift the intervals now. However you can select any range in the histogram and highlight the points in selection, so you can play with the plots to test any range for patterns.

**Comment by vestlink** [comment]
thank you for your feedback on the matter. I will have to think about the subject a bit more...
