### ISSUE TITLE
Test deployment in various environment

### ISSUE THREAD

**Issue by xhdong-umd** [ctmm-initiative/ctmm-webapp#20]
I will test all the deployment options with different environments in the following week, and test again before the Animov course in August.

This is to make sure all features worked, and there is no significant problem in UI because of browser/system difference.

- hosted app
  + Test different browsers (safari, firefox, IE, chrome) in Mac OS, Windows and Linux.
  + After we signed up basic plan in shinyapps.io, run load test to see how many concurrent users can be supported for heavy and light tasks.
- local app
  + Test with fresh R installation in Mac OS, Windows and Linux

After the test we can have more thorough install instructions, and maybe provide a FAQ for deployment problems.

**Comment by vestlink** [comment]
I can test on macos, windows 8 and 10 and linux mint if you would like test done by external sources. I can use the internal data as well as the sheep data i have from two separate areas spanning several years and sampled at 30 mins and 1 hour.

**Comment by xhdong-umd** [comment]
@vestlink Thanks for the help! Any test is welcome. 

I plan to make some internal test and add more help documentations first, then release a version in next week. Then we can test that version.

**Comment by vestlink** [comment]
Excellent

**Comment by jmcalabrese** [comment]
@xhdong-umd: This all sounds good. I assume you have all of the different os/browser combinations available to you? If not, I could test on mac os and ubuntu linux.

@vestlink: Thanks for the offer! External testing, especially with new data, would be great.

**Comment by xhdong-umd** [comment]
I can use the Macbook and my home windows PC. I also prepared to install linux VM for testing.

I think I will test the major platform for app behavior, and any other contributed test with different data will be very useful.

**Comment by vestlink** [comment]
Vm is Very useful for this. Iwrote about this I  the collaborative animove
article.

**Comment by vestlink** [comment]
For testing purposes it would be usefull if testers (like me) would have one or a set of test scenarios that you want the testers to go through including guidelines regarding the amount of data and what logs you are interested in, e.g. sessionInfo() and so on. I think it will help to backtrack and troubleshoot your application. Nicolai

**Comment by vestlink** [comment]
i found this site f.y.i. http://www.osboxes.org

**Comment by xhdong-umd** [comment]
Yes I have used the VM images there before. It still often took me quite some time to adjust a Linux to a easy to use state: resolution, font, shell, term, install softwares, editors, ... 

Installing Linux itself actually is not too time consuming.

**Comment by vestlink** [comment]
it would have been nice to have a vm image together with the release of every new R version...

**Comment by vestlink** [comment]
I got a ubuntu 16.10 from osboxes.org working with R 3.4.0 and RStudio and ctmm using the following:

https://mikewilliamson.wordpress.com/2016/11/14/installing-r-studio-on-ubuntu-16-10/
https://www.r-bloggers.com/how-to-install-r-on-linux-ubuntu-16-04-xenial-xerus/
http://stackoverflow.com/questions/20923209/problems-installing-the-devtools-package
https://github.com/domlysz/BlenderGIS/wiki/How-to-install-GDAL
http://stackoverflow.com/questions/15248815/rgdal-package-installation

I'd be happy to uploade my virtualbox to Dropbox if it would be of interest.

Nicolai

**Comment by xhdong-umd** [comment]
@vestlink Thanks for the offer!

There are two aspects in my testing goals. 
- One is the deployment process, i.e. to get the app up and running. After the app is running, it's mostly browser's behavior. Browser should be quite consistent across platform, so I don't think we have to test with all browser/platform combinations.

  For example @jmcalabrese found the log scale slider in visual diagnostic page didn't work in RStudio browser in Linux. I tested with Windows 10 last night, the RStudio browser in windows has same problem. Firefox and Chrome in Linux and windows don't have this problem. 

  Browser compatibility can be quite tricky and I don't have time to inspect at this time. We probably can only acknowledge the problem and suggest users to use a compatible browser for now.

- Another part is the app behavior with different data sets and usage. Here external tests will be very helpful. I created an new issue for this #23.

For the local deployment, we need to install about 30 dependency packages in a fresh R installation. I want to make sure this process is as smooth as possible.

So if you can help test the linux platform, I'll want to start from a bare bone R installation, with only R and RStudio installed.

You can use `packrat` to simulate a vanilla R installation:

0. with later version of R and RStudio installed
1. create an new RStudio project in new folder
2. setup `packrat` to create a isolated R library environment

```r
install.packages("packrat")
# current working directory should be project directory. You can also specify the folder path.
packrat::init()
```

3. install dependency packages:

```r
if (!require("devtools"))
  install.packages("devtools")
devtools::install_github("rstudio/shiny")
# restart R session and run this again if have error
devtools::install_github("ctmm-initiative/ctmm")

shiny::runGitHub('ctmm-initiative/ctmm-webapp')
```

I tested this process in Macbook and my windows PC. 

In windows 10 I need to restart R session once and run ctmm install script second time. Other than this it's mostly smooth.

I'm not sure if this will work smoothly in linux, so if you can help test this it will be very helpful. 

Thanks!

**Comment by vestlink** [comment]
I Will look into this asap but prob in about 4-5 hours from now

**Comment by xhdong-umd** [comment]
@vestlink Thanks a lot for the help!

I also tested above procedure in Macbook, it went smoothly. Of course there could still be some difference in Mac OS version etc, but I think this should be enough for platform tests. Testing app with different data probably will reveal more problems need to be fixed.

**Comment by vestlink** [comment]
https://www.dropbox.com/sh/v5q9kd2jb6xryk7/AADUKqM_4KLpdeP-4DFz-RiRa?dl=0

**Comment by xhdong-umd** [comment]
@vestlink Is posting the data publicly OK for you? You can send the link to my email if you want.

**Comment by vestlink** [comment]
Publicity would be ok.  They are at movebank anyway :) but I will ask my
supervisor

**Comment by vestlink** [comment]
The updated repo is working on my data that failed previously.

I do notice this though:

Warning in structure(x, class = unique(c("AsIs", oldClass(x)))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
Warning in structure(x, class = unique(c("AsIs", oldClass(x)))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
Warning in structure(x, class = unique(c("AsIs", oldClass(x)))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
Warning in structure(x, class = unique(c("AsIs", oldClass(x)))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
Warning in structure(x, class = unique(c("AsIs", oldClass(x)))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
Warning in structure(x, class = unique(c("AsIs", oldClass(x)))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
Warning in structure(x, class = unique(c("AsIs", oldClass(x)))) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.

**Comment by xhdong-umd** [comment]
I noticed that warning too. It happened in removing outliers, but does not always happen. I'll look at it when it can be reproduced.

**Comment by xhdong-umd** [comment]
@jmcalabrese @chfleming 
I realized you don't really need RStudio to run a Shiny app, and tested with my app in command line successfully. So it's possible to write some script to automate the package upgrades, app download and app launching.

This means a user not familiar with R can just install R (which has installers for each platform, should not be a problem to install), then run some script and our app could start running. It may also be possible to pack everything into one installer.

I'll look into this later.

**Comment by xhdong-umd** [comment]
@vestlink I found the cause of that warning, which is R 3.4 start to warn the usage of `I(NULL)`. It's in the upstream package `DT`, but I changed my code anyway to avoid the warning.

**Comment by vestlink** [comment]
@xhdong-umd thank you for your information regarding the warning issues.

**Comment by xhdong-umd** [comment]
I found [my bug report to shiny DT](https://github.com/rstudio/DT/issues/421) was misidentified as a duplication, so they didn't really fix the bug. I changed my code so it should avoid the warning completely now. I also reminded them again about the bug.

**Comment by xhdong-umd** [comment]
I finally got Linux Mint working in virtualbox. Ubuntu created a lot of problems for me but Linux Mint is very smooth.

Other than some R package installation minor problems, the app is running well under Linux, including the parallel computing mode.

**Comment by xhdong-umd** [comment]
I made the installation commands into a script, and instruct users to use one line in R console to install package and run the app.  It should be much easier for user: just install R and run one line.

**Comment by xhdong-umd** [comment]
I tested the app in windows and found a bug relate to windows path separator. The bug has been fixed, and I have updated the repo and the hosted web app.
