### ISSUE TITLE
export to shapefiles

### ISSUE THREAD

**Issue by vestlink** [ctmm-initiative/ctmm-webapp#31]
Won't work and i get this in the stack trace.

R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[R.app GUI 1.70 (7375) x86_64-apple-darwin15.6.0]

[Workspace restored from /Users/nicolaijorgensen/.RData]
[History restored from /Users/nicolaijorgensen/.Rapp.history]

> source("https://raw.githubusercontent.com/ctmm-initiative/ctmm-webapp/master/run.R")
Loading required package: devtools
Downloading GitHub repo rstudio/shiny@master
from URL https://api.github.com/repos/rstudio/shiny/zipball/master
Installing shiny
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/qw/xjq4_wxj239b56vwdtj7gjhh0000gn/T/RtmpXnJ9Ie/devtools97be38f5475e/rstudio-shiny-dc18b20'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘shiny’ ...
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (shiny)
Downloading GitHub repo ctmm-initiative/ctmm@master
from URL https://api.github.com/repos/ctmm-initiative/ctmm/zipball/master
Installing ctmm
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/qw/xjq4_wxj239b56vwdtj7gjhh0000gn/T/RtmpXnJ9Ie/devtools97be332bd203/ctmm-initiative-ctmm-bf2675e'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘ctmm’ ...
** R
** data
** inst
** preparing package for lazy loading
Creating a generic function for ‘projection’ from package ‘raster’ in package ‘ctmm’
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (ctmm)
Downloading https://github.com/ctmm-initiative/ctmm-webapp/archive/master.tar.gz
Loading required package: shiny
Loading required package: pacman

Listening on http://127.0.0.1:5750
Maximum speed of 0.932 m/s observed in 71608843
Minimum sampling interval of 60 minutes in 71608843
Maximum speed of 0.675 m/s observed in 71608847
Minimum sampling interval of 60 minutes in 71608847
Maximum speed of 2.77 m/s observed in 71608850
Minimum sampling interval of 60 minutes in 71608850
Maximum speed of 2.77 m/s observed in 71608853
Minimum sampling interval of 60 minutes in 71608853
Maximum speed of 0.998 m/s observed in 71608856
Minimum sampling interval of 60 minutes in 71608856
Maximum speed of 3.11 m/s observed in 71608859
Minimum sampling interval of 60 minutes in 71608859
Maximum speed of 0.912 m/s observed in 71608862
Minimum sampling interval of 60 seconds in 71608862
Maximum speed of 2.79 m/s observed in 71608865
Minimum sampling interval of 60 minutes in 71608865
Maximum speed of 0.948 m/s observed in 71608868
Minimum sampling interval of 60 minutes in 71608868
Maximum speed of 0.947 m/s observed in 71608871
Minimum sampling interval of 60 minutes in 71608871
Maximum speed of 2.79 m/s observed in 71608874
Minimum sampling interval of 60 minutes in 71608874
Maximum speed of 2.77 m/s observed in 71608877
Minimum sampling interval of 60 minutes in 71608877
Maximum speed of 0.0402 m/s observed in 71608881
Minimum sampling interval of 22 hours in 71608881
Maximum speed of 0.614 m/s observed in 71608884
Minimum sampling interval of 60 minutes in 71608884
Maximum speed of 0.573 m/s observed in 71608887
Minimum sampling interval of 60 minutes in 71608887
Maximum speed of 1.05 m/s observed in 71608890
Minimum sampling interval of 30 minutes in 71608890
Maximum speed of 1.62 m/s observed in 71608893
Minimum sampling interval of 30 minutes in 71608893
Maximum speed of 1.2 m/s observed in 71608896
Minimum sampling interval of 30 minutes in 71608896
Maximum speed of 2.97 m/s observed in 71608899
Minimum sampling interval of 30 minutes in 71608899
Maximum speed of 1.14 m/s observed in 71608902
Minimum sampling interval of 30 minutes in 71608902
Maximum speed of 0.98 m/s observed in 71608905
Minimum sampling interval of 30 minutes in 71608905
Maximum speed of 2.81 m/s observed in 71610139
Minimum sampling interval of 34 minutes in 71610139
Maximum speed of 0.994 m/s observed in 71610143
Minimum sampling interval of 60 minutes in 71610143
Maximum speed of 1.86 m/s observed in 71610146
Minimum sampling interval of 60 minutes in 71610146
Maximum speed of 2.91 m/s observed in 71610149
Minimum sampling interval of 60 minutes in 71610149
Maximum speed of 0.554 m/s observed in 71610152
Minimum sampling interval of 33 minutes in 71610152
Maximum speed of 0.648 m/s observed in 71610155
Minimum sampling interval of 5 minutes in 71610155
Maximum speed of 2.98 m/s observed in 71610158
Minimum sampling interval of 24 minutes in 71610158
Maximum speed of 1.57 m/s observed in 71610161
Minimum sampling interval of 60 minutes in 71610161
Maximum speed of 1.54 m/s observed in 71610164
Minimum sampling interval of 60 minutes in 71610164
Maximum speed of 2.82 m/s observed in 71610167
Minimum sampling interval of 60 minutes in 71610167
Maximum speed of 0.751 m/s observed in 71610170
Minimum sampling interval of 60 minutes in 71610170
Maximum speed of 1.99 m/s observed in 71610173
Minimum sampling interval of 60 minutes in 71610173
Maximum speed of 1.18 m/s observed in 71610176
Minimum sampling interval of 60 minutes in 71610176
Maximum speed of 1.99 m/s observed in 71610179
Minimum sampling interval of 60 minutes in 71610179
Maximum speed of 2.89 m/s observed in 71610182
Minimum sampling interval of 60 minutes in 71610182
Maximum speed of 0.755 m/s observed in 71610185
Minimum sampling interval of 60 minutes in 71610185
Maximum speed of 4.72 m/s observed in 71610188
Minimum sampling interval of 30 minutes in 71610188
Maximum speed of 5.25 m/s observed in 71610191
Minimum sampling interval of 30 minutes in 71610191
Maximum speed of 4.35 m/s observed in 71610194
Minimum sampling interval of 30 minutes in 71610194
Maximum speed of 4.71 m/s observed in 71610197
Minimum sampling interval of 30 minutes in 71610197
Maximum speed of 7.08 m/s observed in 71610200
Minimum sampling interval of 60 seconds in 71610200
Maximum speed of 0.923 m/s observed in 71610203
Minimum sampling interval of 60 seconds in 71610203
Maximum speed of 2.84 m/s observed in 71610206
Minimum sampling interval of 30 minutes in 71610206
Maximum speed of 4.65 m/s observed in 71610209
Minimum sampling interval of 30 minutes in 71610209
Maximum speed of 6.93 m/s observed in 71610212
Minimum sampling interval of 30 minutes in 71610212
Maximum speed of 4.63 m/s observed in 71610215
Minimum sampling interval of 30 minutes in 71610215
Maximum speed of 7.19 m/s observed in 71610218
Minimum sampling interval of 30 minutes in 71610218
Maximum speed of 5.26 m/s observed in 71610221
Minimum sampling interval of 30 minutes in 71610221
Warning: The shape palette can deal with a maximum of 6 discrete values because
more than 6 becomes difficult to discriminate; you have 49. Consider
specifying shapes manually if you must have them.
Warning: Removed 47 rows containing missing values (geom_point).
running parallel with mclapply in cluster of 1 
* Fitting models OUF anisotropic
Maximizing likelihood.
Calculating covariance.
   user  system elapsed 
 11.700   0.141  11.927 
running parallel with mclapply in cluster of 1 
   user  system elapsed 
 39.802   2.042  41.934 
Warning in CI.UD(x, max(level.UD), max(level), P = TRUE) :
  Outer contour extends beyond raster.
Warning in CI.UD(x[[i]], l, level, P = TRUE) :
  Outer contour extends beyond raster.
Warning in log(alpha.UD) : NaNs produced
Warning: Error in validObject: invalid class “SpatialPolygons” object: non-unique Polygons ID slot values
Stack trace (innermost first):
    65: validObject
    64: sp::SpatialPolygons
    63: SpatialPolygonsDataFrame.UD
    62: writeShapefile.UD
    61: writeShapefile
    60: FUN [/private/var/folders/qw/xjq4_wxj239b56vwdtj7gjhh0000gn/T/RtmpXnJ9Ie/shinyapp97be5f1281e6/ctmm-webapp-master/server.R#1562]
    59: lapply
    58: write_f [/private/var/folders/qw/xjq4_wxj239b56vwdtj7gjhh0000gn/T/RtmpXnJ9Ie/shinyapp97be5f1281e6/ctmm-webapp-master/server.R#1561]
    57: build_zip [helpers.R#611]
    56: download$func [/private/var/folders/qw/xjq4_wxj239b56vwdtj7gjhh0000gn/T/RtmpXnJ9Ie/shinyapp97be5f1281e6/ctmm-webapp-master/server.R#1569]
     7: runApp
     6: runUrl
     5: shiny::runGitHub
     4: eval [https://raw.githubusercontent.com/ctmm-initiative/ctmm-webapp/master/run.R#7]
     3: eval
     2: withVisible
     1: source
Error : invalid class “SpatialPolygons” object: non-unique Polygons ID slot values

**Comment by xhdong-umd** [comment]
@vestlink What's the exact procedures to reach this error?

I tried the data `Movebank 70397061 - A week in the life of a pygmy blue whale` (I assume it's the same data since the import message was same), fit models, checked home ranges with default first page, and didn't see this error.

**Comment by vestlink** [comment]
@xhdong-umd I was using my 70397061  Ovis aries, Nordøsterdalen, Norway data.

I think there must be something wrong with the dataset.

101684640 | Ovis aries, Hol, Buskerud, Norway works fine...

**Comment by xhdong-umd** [comment]
It seemed that there was some errors in generating the polygons for home range. Which individual did you choose in the test? I guess it was not in first page which I tested.

The data I used came from a movebank export before, which is the 70397061 data but with fewer columns.

**Comment by vestlink** [comment]
I Think it was the 4th animal

**Comment by xhdong-umd** [comment]
I tried again with the 4th animal but didn't see any error. Can you share the data file so I can test on it?

**Comment by vestlink** [comment]
[sheep.zip](https://github.com/ctmm-initiative/ctmm-webapp/files/1300234/sheep.zip)

The 70397061 was named 127.0.0.1 when i tried to save it after download

**Comment by vestlink** [comment]
i think the error occurred when I tried to add 20, 50 and 95 in the % Contour level of Home Range, and then tried to export that shapefile. Mayby the same ID was assigned to each layer (ERROR: invalid class “SpatialPolygons” object: non-unique Polygons ID slot values)

**Comment by xhdong-umd** [comment]
@chfleming I can reproduce this error:

1. use 70397061 data (127.0.0.1 file in sheep.zip above), select the 4th animal
2. fit model, calculate home range
3. add `20, 50, 95` to Contour level, export shapefile.

I found `50, 95` is working fine. I noticed that `20` actually are not shown in the plot (maybe not valid?).

**Comment by chfleming** [comment]
Seems to work fine now.

**Comment by xhdong-umd** [comment]
I verified it too. Thanks!

**Comment by vestlink** [comment]
Works fine now...
