### ISSUE TITLE
Shapefile Export fails with multiple models selected

### ISSUE THREAD

**Issue by regan-sarwas** [ctmm-initiative/ctmm-webapp#32]
Stack trace on console:
```
Warning: Error in rgdal::writeOGR: layer exists, use a new layer name
Stack trace (innermost first):
    57: rgdal::writeOGR
    56: writeShapefile.UD
    55: writeShapefile
    54: FUN [/Users/regan_sarwas/MyForks/ctmm-webapp/server.R#1562]
    53: lapply
    52: write_f [/Users/regan_sarwas/MyForks/ctmm-webapp/server.R#1561]
    51: build_zip [helpers.R#611]
    50: download$func [/Users/regan_sarwas/MyForks/ctmm-webapp/server.R#1569]
     1: runApp
Error : layer exists, use a new layer name
```

Steps to reproduce:

1.  open [hosted app](https://ctmm.shinyapps.io/ctmmweb/) (stack trace is from 18a6b21a2a8c2cf469df22fdda43648fed60e1ed)
2. Select `Use Sample of Buffalo Data`
3. Select `Cilla`
4. Fit Model
5. Select both `OU anisotropic` and `OUF anisotropic` models
6. Preview 2 home range plots
7. Click `Export Shapefiles`

Shapefile export works fine with multiple animals, just not multiple models per animal.

**Comment by xhdong-umd** [comment]
Thanks for the report! The code used individual name as shapefile name. I have updated it to include the model name and tested it works.

**Comment by regan-sarwas** [comment]
@xhdong-umd, Thanks for the speedy fix.  It works great.
