### ISSUE TITLE
Time subsetting

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmm-webapp#37]
When using the current version of the hosted web app, the time subsetting feature is not functioning.

Attached is a screenshot of the error
![screen shot 2017-10-23 at 2 10 53 pm 2](https://user-images.githubusercontent.com/26824892/31905392-0c1dd4c8-b7fc-11e7-9e26-2a2edd440fd9.png)

**Comment by xhdong-umd** [comment]
@NoonanM You need to select single animal for this page. All other pages will react to current selected animals (or current page in the animal table if nothing selected), but time subsetting is difficult to work with multiple animals, so there is this condition.

This is explained in the red notification message and help window.

**Comment by NoonanM** [comment]
@xhdong-umd OK, I see now. Is it possible to add a feature for selecting individuals from that page?

**Comment by xhdong-umd** [comment]
That will need a table of individuals, which is duplicate from visualization page. User may also want to check the various plots to determine which individual he/she want to subset in time, so I think it's best to still come back to visualization page.

**Comment by chfleming** [comment]
If there isn't going to be an animal selector here, I think the user needs more guidance for the user. Maybe a link back to the visualization tab or maybe better grey out & make inactive tabs that aren't available when the right number of animals aren't selected + when on-mouse-hover over the inactive tabs then tell users what is required for that analysis tab.

**Comment by xhdong-umd** [comment]
There is a notification message "Please select single animal" that will stay on top of page for quite some time, which should not be missed by user. 

I can make the message more specific like "Please select single animal in Visualization".

There is no easy grey out/inactive methods in Shiny that I know. I think the empty boxes should serve similar purpose.

**Comment by NoonanM** [comment]
If you click on the ?help box, you get all the information you need. Maybe you can add some default text that says something like "More than one individual currently selected. See ?Help box for more information", or even make some of the help text the default view when more than one individual is selected?

**Comment by xhdong-umd** [comment]
Do you mean show some text inside a box? That's doable but I'm not sure which is better, pop up message or show error information inside a box.

I can also pop up the help window automatically, but that could be a little bit overwhelming when user knew the limit already but forgot to select single individual first.

Another improvement is to switch back to visualization page automatically and show the pop up message, so it's a little bit easier for user.

**Comment by NoonanM** [comment]
I had the same thought about making the help window pop up automatically, but I think you're right, it would be too much.

Instead of repeating the table from the visualization tab, maybe having a drop down menu of individuals like when you select "Fine-tune" to guesstimate a fit would be a solution? It would make the tab functional on its own without having to back to the visualization tab.

**Comment by xhdong-umd** [comment]
I still think move back to visualization tab is more useful, otherwise user need to remember which one he/she want by name, sometimes the names are just numbers. 

Now the app will switch page automatically, so it's also easier for user. The page switch will definitely catch user's attention and make him/her notice the notification message too.

**Comment by NoonanM** [comment]
It's a little bit buggy. I select cilla, move to the Time Subset page, and it starts fine, but takes me back to the Visualization page after a few seconds.

Also, now the user has no chance to read the help box on the page before selecting an individual.

**Comment by xhdong-umd** [comment]
Sorry there was a mistake. Fixing now.

I considered the limit of user cannot read the help page before selecting single individual. I thought if user will read the help page, then everything we are discussing here is not needed. 

So the assumption is user often do not read the help before meet this problem. Now user is forced to select single individual first, after that he/she can read the help page. The automatic page switching save some click and some time, which should be more important. Myself often forget to select single individual before time subsetting, so the automatic page switch definitely helps.
