### ISSUE TITLE
Individual Plotting

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmm-webapp#38]
When plotting individual data on the 'Visualization' tab the app generates an error. See attached screen shot.

To reproduce the error, select "Use Sample of Buffalo Data", set n to 100, and attempt visualization of individual data.

![screen shot 2017-10-23 at 2 13 03 pm 2](https://user-images.githubusercontent.com/26824892/31905487-54da7dd8-b7fc-11e7-8fc2-f36b00f804f6.png)

**Comment by xhdong-umd** [comment]
There is a bug in plot arrangement when the individual count is not divided by the columns. I've fixed the bug, but may push the changes later after the change on data import.
