### ISSUE TITLE
Import data

### ISSUE THREAD

**Issue by NoonanM** [ctmm-initiative/ctmm-webapp#39]
When importing data via "Use Sample of Buffalo Data", if the user first sets n = 100, then goes back to change the sample size to eg. n = 500, the app is not updating.

**Comment by xhdong-umd** [comment]
The app is watching the event of selecting "sample" mode, then read the current value of sample size.

If you are already in "sample" mode, just changing the sample size will not trigger the event thus nothing happened. You can work around this by switch to "upload", change sample size then switch back to "sample" mode.

If this usage is common for users, I can add some code to further watch the sample size, and update the app if it's in "sample" mode.

**Comment by NoonanM** [comment]
@xhdong-umd I don't think it's going to be common behaviour, but we use this functionality regularly when giving demos of the app.

@chfleming @jmcalabrese What do you think about adaptive "sample" mode?

**Comment by xhdong-umd** [comment]
If you guys use this frequently I'll add it. I use the sample mode all the time, just didn't change sample size much.

**Comment by xhdong-umd** [comment]
Now the app will observe the update in sample size if already in sample mode. I'm still in the process of updating web app, since it take some time to finish.
